library("aitoaEvaluate");
library("testthat");
context("aitoa.algo.setup");

test_that("Test aitoa.algorithm.parameters", {
  r1 <- aitoa.algorithm.parameters.rs("rs");
  r2 <- aitoa.algorithm.parameters("rs");
  expect_identical(r1, r2);
  expect_identical(r1$algo.name, "rs");
  expect_identical(r1$algo.algorithm, "rs");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.mu, 0L);
  expect_identical(r1$algo.lambda, 1L);
  expect_identical(r1$algo.binary.rate, 0);
  expect_identical(r1$algo.restarts, TRUE);
  expect_identical(r1$algo.restarts.strategy, "FEbased");
  expect_identical(r1$algo.restarts.iterations, 1L);
  expect_identical(r1$algo.restarts.incrementFactor, 0);

  r1 <- aitoa.algorithm.parameters.rs("1rs");
  r2 <- aitoa.algorithm.parameters("1rs");
  expect_identical(r1, r2);
  expect_identical(r1$algo.name, "1rs");
  expect_identical(r1$algo.algorithm, "rs");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.mu, 0L);
  expect_identical(r1$algo.lambda, 1L);
  expect_identical(r1$algo.binary.rate, 0);
  expect_identical(r1$algo.restarts, FALSE);

  r1 <- aitoa.algorithm.parameters.hc("hc_1swapR");
  r2 <- aitoa.algorithm.parameters("hc_1swapR");
  expect_identical(r1, r2);
  expect_identical(r1$algo.name, "hc_1swap");
  expect_identical(r1$algo.algorithm, "hc");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.restarts, FALSE);
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.mu, 1L);
  expect_identical(r1$algo.lambda, 1L);
  expect_identical(r1$algo.binary.rate, 0);

  r1 <- aitoa.algorithm.parameters.hc("hc_rs_256_0d05_1swapR");
  r2 <- aitoa.algorithm.parameters("hc_rs_256_0d05_1swapR");
  expect_identical(r1, r2);
  expect_identical(r1$algo.name, "hcr_256+5%_1swap");
  expect_identical(r1$algo.algorithm, "hc");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.restarts.strategy, "FEbased");
  expect_identical(r1$algo.restarts.iterations, 256L);
  expect_identical(r1$algo.restarts.incrementFactor, 0.05);
  expect_identical(r1$algo.restarts, TRUE);
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.mu, 1L);
  expect_identical(r1$algo.lambda, 1L);
  expect_identical(r1$algo.binary.rate, 0);

  r1 <- aitoa.algorithm.parameters.hc("hc_rs_mxn_0d05_1swapR");
  r2 <- aitoa.algorithm.parameters("hc_rs_mxn_0d05_1swapR");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "hc");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.restarts.strategy, "FEbased");
  expect_identical(r1$algo.restarts.iterations, "mxn");
  expect_identical(r1$algo.restarts.incrementFactor, 0.05);
  expect_identical(r1$algo.restarts, TRUE);
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.mu, 1L);
  expect_identical(r1$algo.lambda, 1L);
  expect_identical(r1$algo.binary.rate, 0);

  r1 <- aitoa.algorithm.parameters.sa("sa_exp_20_0d0000002_1swapR");
  r2 <- aitoa.algorithm.parameters("sa_exp_20_0d0000002_1swapR");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "sa");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.temperature.schedule, "exp");
  expect_identical(r1$algo.temperature.start, 20L);
  expect_identical(r1$algo.temperature.parameter, 0.0000002);
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.mu, 1L);
  expect_identical(r1$algo.lambda, 1L);
  expect_identical(r1$algo.binary.rate, 0);

  r1 <- aitoa.algorithm.parameters.ea("eap_16+16@0d3_1swapR_sequence");
  r2 <- aitoa.algorithm.parameters("eap_16+16@0d3_1swapR_sequence");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "ea");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.operator.binary, "sequence");
  expect_identical(r1$algo.mu, 16L);
  expect_identical(r1$algo.lambda, 16L);
  expect_identical(r1$algo.binary.rate, 0.3);
  expect_identical(r1$algo.fitness, "pruning");
  expect_identical(r1$algo.is.hybrid, FALSE);

  r1 <- aitoa.algorithm.parameters.ea("ea_ffa_16+16@0d3_1swapR_sequence");
  r2 <- aitoa.algorithm.parameters("ea_ffa_16+16@0d3_1swapR_sequence");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "ea");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.operator.binary, "sequence");
  expect_identical(r1$algo.mu, 16L);
  expect_identical(r1$algo.lambda, 16L);
  expect_identical(r1$algo.binary.rate, 0.3);
  expect_identical(r1$algo.fitness, "ffa");
  expect_identical(r1$algo.is.hybrid, FALSE);

  r1 <- aitoa.algorithm.parameters.ea("ea_16+16@0d3_1swapR_sequence");
  r2 <- aitoa.algorithm.parameters("ea_16+16@0d3_1swapR_sequence");
  expect_identical(r1, r2);
  expect_identical(r1$algo.name, "ea16_1swap_30s");
  expect_identical(r1$algo.algorithm, "ea");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.operator.binary, "sequence");
  expect_identical(r1$algo.mu, 16L);
  expect_identical(r1$algo.lambda, 16L);
  expect_identical(r1$algo.binary.rate, 0.3);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.is.hybrid, FALSE);

  r1 <- aitoa.algorithm.parameters.ma("ma_16+16_1swapR_sequence");
  r2 <- aitoa.algorithm.parameters("ma_16+16_1swapR_sequence");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "ma");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.operator.binary, "sequence");
  expect_identical(r1$algo.mu, 16L);
  expect_identical(r1$algo.lambda, 16L);
  expect_identical(r1$algo.binary.rate, 1L);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.is.hybrid, TRUE);
  expect_identical(r1$algo.hybrid.global.search, "ea");

  r1 <- aitoa.algorithm.parameters.ma("map_16+16_1swapR_sequence");
  r2 <- aitoa.algorithm.parameters("map_16+16_1swapR_sequence");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "ma");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.operator.binary, "sequence");
  expect_identical(r1$algo.mu, 16L);
  expect_identical(r1$algo.lambda, 16L);
  expect_identical(r1$algo.binary.rate, 1L);
  expect_identical(r1$algo.fitness, "pruning");
  expect_identical(r1$algo.is.hybrid, TRUE);
  expect_identical(r1$algo.hybrid.global.search, "ea");

  r1 <- aitoa.algorithm.parameters.ma("ma_ffa_16+26_1swapR_sequence");
  r2 <- aitoa.algorithm.parameters("ma_ffa_16+26_1swapR_sequence");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "ma");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "1swapR");
  expect_identical(r1$algo.operator.binary, "sequence");
  expect_identical(r1$algo.mu, 16L);
  expect_identical(r1$algo.lambda, 26L);
  expect_identical(r1$algo.binary.rate, 1L);
  expect_identical(r1$algo.fitness, "ffa");
  expect_identical(r1$algo.is.hybrid, TRUE);
  expect_identical(r1$algo.hybrid.global.search, "ea");

  r1 <- aitoa.algorithm.parameters.eda("eda_umda_1024+2048");
  r2 <- aitoa.algorithm.parameters("eda_umda_1024+2048");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "eda");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.mu, 1024L);
  expect_identical(r1$algo.lambda, 2048L);
  expect_identical(r1$algo.model, "umda");
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.is.hybrid, FALSE);

  r1 <- aitoa.algorithm.parameters.eda("eda_umda_ffa_1024+2048");
  r2 <- aitoa.algorithm.parameters("eda_umda_ffa_1024+2048");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "eda");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.mu, 1024L);
  expect_identical(r1$algo.lambda, 2048L);
  expect_identical(r1$algo.fitness, "ffa");
  expect_identical(r1$algo.model, "umda");
  expect_identical(r1$algo.is.hybrid, FALSE);

  r1 <- aitoa.algorithm.parameters.heda("heda_umda_1024+2048_1swapR");
  r2 <- aitoa.algorithm.parameters("heda_umda_1024+2048_1swapR");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "eda");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.mu, 1024L);
  expect_identical(r1$algo.lambda, 2048L);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.is.hybrid, TRUE);
  expect_identical(r1$algo.hybrid.global.search, "eda");
  expect_identical(r1$algo.model, "umda");
  expect_identical(r1$algo.operator.unary, "1swapR");

  r1 <- aitoa.algorithm.parameters.heda("heda_umda_ffa_1024+2048_1swapR");
  r2 <- aitoa.algorithm.parameters("heda_umda_ffa_1024+2048_1swapR");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "eda");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.mu, 1024L);
  expect_identical(r1$algo.lambda, 2048L);
  expect_identical(r1$algo.fitness, "ffa");
  expect_identical(r1$algo.is.hybrid, TRUE);
  expect_identical(r1$algo.hybrid.global.search, "eda");
  expect_identical(r1$algo.model, "umda");
  expect_identical(r1$algo.operator.unary, "1swapR");

  r1 <- aitoa.algorithm.parameters.hc2("hc2f_rs_12swapR");
  r2 <- aitoa.algorithm.parameters("hc2f_rs_12swapR");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "hc2");
  expect_identical(r1$algo.representation, "default");
  expect_identical(r1$algo.operator.unary, "12swapR");
  expect_identical(r1$algo.restarts.strategy, "after.enumeration");
  expect_identical(r1$algo.restarts, TRUE);
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.mu, 1L);
  expect_identical(r1$algo.lambda, 1L);
  expect_identical(r1$algo.binary.rate, 0);


  r1 <- aitoa.algorithm.parameters.gp("gp8_ea_1024+3024@0d05");
  r2 <- aitoa.algorithm.parameters("gp8_ea_1024+3024@0d05");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "ea");
  expect_identical(r1$algo.representation, "tree");
  expect_identical(r1$algo.operator.unary, "tree1");
  expect_identical(r1$algo.operator.binary, "tree2");
  expect_identical(r1$algo.max.tree.depth, 8L);
  expect_identical(r1$algo.restarts, FALSE);
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.mu, 1024L);
  expect_identical(r1$algo.lambda, 3024L);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.binary.rate, 0.05);


  r1 <- aitoa.algorithm.parameters.gp("gp8_sa_log_10_1");
  r2 <- aitoa.algorithm.parameters("gp8_sa_log_10_1");
  expect_identical(r1, r2);
  expect_identical(r1$algo.algorithm, "sa");
  expect_identical(r1$algo.representation, "tree");
  expect_identical(r1$algo.operator.unary, "tree1");
  expect_identical(r1$algo.max.tree.depth, 8L);
  expect_identical(r1$algo.restarts, FALSE);
  expect_identical(r1$algo.is.hybrid, FALSE);
  expect_identical(r1$algo.mu, 1L);
  expect_identical(r1$algo.lambda, 1L);
  expect_identical(r1$algo.binary.rate, 0);
  expect_identical(r1$algo.fitness, "direct");
  expect_identical(r1$algo.temperature.schedule, "log");
  expect_identical(r1$algo.temperature.start, 10L);
  expect_identical(r1$algo.temperature.parameter, 1L);
})

